// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfV_Z3G_dBxmNfOidtLFkfLQW-9THkrN8',
    appId: '1:391217637721:web:42a15e44a36c75bbd48448',
    messagingSenderId: '391217637721',
    projectId: 'navigation-98ec4',
    authDomain: 'navigation-98ec4.firebaseapp.com',
    storageBucket: 'navigation-98ec4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChv2ITVfXBUkwVopl1Eroms9SFZSILzdc',
    appId: '1:391217637721:android:b7dfcae3f61c0961d48448',
    messagingSenderId: '391217637721',
    projectId: 'navigation-98ec4',
    storageBucket: 'navigation-98ec4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCy2tiCm1TJQN2o8UGgocqmMd3mZ_daj0',
    appId: '1:391217637721:ios:6c6920f7430300f8d48448',
    messagingSenderId: '391217637721',
    projectId: 'navigation-98ec4',
    storageBucket: 'navigation-98ec4.firebasestorage.app',
    iosBundleId: 'com.example.tryout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCy2tiCm1TJQN2o8UGgocqmMd3mZ_daj0',
    appId: '1:391217637721:ios:6c6920f7430300f8d48448',
    messagingSenderId: '391217637721',
    projectId: 'navigation-98ec4',
    storageBucket: 'navigation-98ec4.firebasestorage.app',
    iosBundleId: 'com.example.tryout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfV_Z3G_dBxmNfOidtLFkfLQW-9THkrN8',
    appId: '1:391217637721:web:f4ac6e24933c5e7cd48448',
    messagingSenderId: '391217637721',
    projectId: 'navigation-98ec4',
    authDomain: 'navigation-98ec4.firebaseapp.com',
    storageBucket: 'navigation-98ec4.firebasestorage.app',
  );
}
